### ISSUE TITLE
Liga de clãs com novos sistemas de rewards

### ISSUE THREAD

**Issue by leogianfagna** [leogianfagna/IssueTracker#1137]
### Descrição da tarefa

Nova atualização de clãs inseriu os dois novos ícones:

![Image](https://github.com/user-attachments/assets/b17199b1-515d-43fa-82f5-d22d1a5fb789)

![Image](https://github.com/user-attachments/assets/096c1c0e-5852-4d5f-805c-6c017c756c1b)

Isso pode ser inserido junto com o addon de liga e criar finalmente a liga de clãs.

Dentro das configs de gui.yml, eles são reconhecidos como:
```yml
      levelup:
        enabled: false
        clicksound: ''
        material: ANVIL
        glow: false
        texture: ''
        amount: 1
        slot: 50
      rewards:
        enabled: false
        clicksound: ''
        material: HOPPER_MINECART
        glow: false
        texture: ''
        amount: 1
        slot: 51
```

# Extra
também agora existe o requirements para níveis de clã, o que pode ser recursos bem interessantes para serem adicionados
