### ISSUE TITLE
Servidor sendo derrubado

### ISSUE THREAD

**Issue by leogianfagna** [leogianfagna/IssueTracker#317]
O anticheat consegue derrubar com isso:
```yml
  transaction:
    kick-enabled: true
    max-delay: 45000
    kick-message: 'Internal Exception: io.netty.handler.timeout.ReadTimeoutException'
    staff-alert-message: '%prefix% &c%player% &7was kicked for not replying to Transaction
      Packets! &7(&c%delay%ms&7)'
    console-message: '[Vulcan] &c%player% &7was kicked for not replying to Transaction
      Packets! &7(&c%delay%ms&7)'
```
![image](https://github.com/austv-minecraft/AusTv/assets/142264317/35fc36b7-fa71-43d2-91dc-8db1b5410975)
https://builtbybit.com/threads/%E2%9C%85-lpx-mortal-1-8-1-120-%E2%9C%85-best-anti-exploit-crasher.627112/
https://mclo.gs/EO7LhlZ
