### ISSUE TITLE
inibir times v.2

### ISSUE THREAD

**Issue by leogianfagna** [leogianfagna/IssueTracker#45]
Descrição: Foi feito o V1 da versão de inibir times. Agora, alguns eventos precisam receber um **versão 2**.

# Eventos que precisam de um v.2
- [x] Guerreirinhos
- [x] Mata Pombo (não dá pra ter armadura)
- [x] Foia: falta o PLAYER_HEAD condizer com o encantamento
- [x] Besta treta (falta binding)

### Patch notes
- Guerreirinhos usa invisibilidade e glowing
- Aplicado invisibilidade no besta treta
- Armadura tem armadura de pomba

Playerhead do Foia:
```
    '39':
      ==: org.bukkit.inventory.ItemStack
      v: 3465
      type: PLAYER_HEAD
      meta:
        ==: ItemMeta
        meta-type: SKULL
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#60918B","text":"Ausevento!"}],"text":""}'
        enchants:
          VANISHING_CURSE: 1
          BINDING_CURSE: 1
        ItemFlags:
        - HIDE_UNBREAKABLE
        - HIDE_DYE
        - HIDE_ENCHANTS #foia
        internal: H4sIAAAAAAAA/+NiYGBkEAjJLEnMK3ZKLCnJSdXzzixhZAAAnkQ9RhgAAAA=
        skull-owner:
          ==: PlayerProfile
          uniqueId: b47f063f-cad5-43d7-89d1-4b1af57d5497
          properties:
          - name: textures
            value: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTdmNjIwY2JlMTNhMWY1NDdkZmMxMmQyNTMyNzk3NDEyOTQxZDk4NzQ4MzFlZmNlYTQ4NjIxMjFiMmE0ODFjYyJ9fX0=
```
