### ISSUE TITLE
Adicionar armaduras na textura normal (hotbar)

### ISSUE THREAD

**Issue by austv** [leogianfagna/IssueTracker#566]
Para tudo funcionar, apesar de não estar na textura, eu givo cada armadura em custom model datas para conseguir reconhecer.
Precisamos adicioná-las na textura oficial com custom model data. Sabemos que sem o optfine não funciona, mas vamos adicionar apenas como forma de item na hotbar. Isso vai fazer também com que jogadores bedrock possam ver a armadura.

![image](https://github.com/austv-minecraft/AusTv/assets/66658478/74669c68-305d-47d3-ab90-6618e732458f)

Pelo o que eu imagino, seja passar esses itens para a textura normal e deixar as layers ainda para o optfine cuidar, mas isso quem sabe melhor é você.

Colocar na textura as seguintes armors nos seguintes customs:
```yml
pascoa 22: custom 1
glacial 22: custom 2
glacial negra 23: custom 3
copa: custom 4 
1 ano: custom 5
carnaval: custom 6
celestial: custom 7
celestial v2: custom 8
desordem: custom 9
insurgente: custom 10
miau: custom 11
natal: custom 12
pascoa: custom 13
ruina: custom 14
samurai: custom 15
tormenta: custom 16
```
